### PR TITLE
Engine Alternator Fix

### PR DESCRIPTION
**Pull request by NyankoSensei**
In the Engine you can't use ModuleCoreHeat but you have to use modulealternator because engine alternator produce energy when the engine is running.
Engine produce Heat and that give problems with every resource converter or generetor you place into it.
Keep the things separated for don't have problems.

### CODE REVIEW

**Comment by luketheyeti** [comment]
ok cool, thanks for the info. I think what I'm going to do is have the engine and engine mount have generators (fuel cell modules) that run on Xenon gas. This will give them a limited lifetime and need to be refueled and maybe let me control when they're on/off and producing electric charge. Do you know how to make the fuel cells generate heat?  I'm looking at the cfgs for the fuel cells and the ISRU and it looks like I can stitch the cfgs together to get something working ;) but it certainly won't be balanced until I understand the pieces.

**Comment by NyankoSensei** [comment]
Fuel cells are resource converters, for base values is enough watch ISRU cfg or Drill cfg.
Drill is good for operate at 500° and ISRU for 1000°, after that you have to balance the ModuleCoreHeat CoretoPartRatio
example ISRU have CoretoPartRatio 0.1 and weight 4.25T, if your part weight 2T with the same thermal values of ModuleResourceConverter you need a CoretoPartRatio of (4.25/2*0.1) 0.2125 otherwise you have to change thermal data for increase-decrease heat production

**Comment by NyankoSensei** [comment]
Closed because outdated

**Comment by luketheyeti** [comment]
Thanks for the info! I have a version working pretty well using the resource converter module and the module core heat. I still need to play with a lot of the values but once I fiddle with a few more things I'll upload here again so other people can look at it.

Also thanks for closing this, I'm still learning how to Git as well ;)

**Pull request closed without merging**
